on: push

jobs:
  build_project:
    environment: dev
    name: Build Project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Azure Bicep Build
        run: az bicep build --file Deployment/deploy.bicep

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: >
            Deployment\Deploy.ps1 
            -StackName ${{ secrets.STACKNAME }} 
            -Location ${{ secrets.LOCATION }}
            -AppEnvironment ${{ secrets.APP_ENVIRONMENT }}
            -Branch ${{ github.ref }}
            -KeyVaultName ${{ secrets.KEY_VAULT_NAME }}
            -DeployResourceGroupName ${{ secrets.DEPLOY_RESOURCE_GROUP_NAME }}
            -KeyVaultResourceGroupName ${{ secrets.KEY_VAULT_RESOURCE_GROUP_NAME }}
            -Domain ${{ secrets.DOMAIN }}
            -ClientId ${{ secrets.CLIENT_ID }}
            -ClientSecret ${{ secrets.CLIENT_SECRET }}
          azPSVersion: "latest"

      - name: Publish, Zip, Deploy
        uses: azure/CLI@v1
        with:
          azcliversion: "latest"
          inlineScript: >
            dotnet publish --configuration Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app'
            Compress-Archive -Path "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app/*" -DestinationPath app.zip
            az webapp deployment source config-zip --resource-group ${{ secrets.DEPLOY_RESOURCE_GROUP_NAME }} --name ${{ secrets.STACKNAME }} --src app.zip