on: push

jobs:
  setup:
    name: Setup Environment
    runs-on: windows-latest
    steps:
      - name: Setup
        run: |
          if [[ '${{ env.github_ref }}' == 'ref/head/main' ]]
          then
            echo "::set-output name=build_env::prod"
          else
            echo "::set-output name=build_env::dev"
          fi
    outputs:
      build_env: ${{ steps.Setup.outputs.build_env }}

  build_project:
    needs: setup
    environment: ${{ needs.setup.outputs.build_env }}
    name: Build Project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Build Azure environment template
        run: az bicep build --file Deployment/deploy.bicep

      - name: Build Azure environment and deploy app
        uses: azure/powershell@v1
        with:
          inlineScript: >
            Deployment\Deploy.ps1 
            -StackName ${{ secrets.STACKNAME }} 
            -Location ${{ secrets.LOCATION }}
            -AppEnvironment ${{ secrets.APP_ENVIRONMENT }}
            -Branch ${{ github.ref }}
            -KeyVaultName ${{ secrets.KEY_VAULT_NAME }}
            -DeployResourceGroupName ${{ secrets.DEPLOY_RESOURCE_GROUP_NAME }}
            -KeyVaultResourceGroupName ${{ secrets.KEY_VAULT_RESOURCE_GROUP_NAME }}
            -Domain ${{ secrets.DOMAIN }}
            -ClientId ${{ secrets.CLIENT_ID }}
            -ClientSecret ${{ secrets.CLIENT_SECRET }}
          azPSVersion: "latest"